### ISSUE TITLE
NE is buggy on under termux - backspace key

### ISSUE THREAD

**Issue by italomaia** [vigna/ne#67] opened 2019-10-18 20:26 UTC
Basically, backspace key doesn't work properly. More info below:

https://github.com/termux/termux-packages/issues/1085

**Comment by craigbarnes** [comment] 2019-10-19 15:26
This seems like a duplicate of issue #48.

**Comment by Salamandar** [comment] 2020-05-05 20:16
Same here, but not on Termux but Archlinux.

**Comment by vigna** [comment] 2020-06-18 12:07
On Mac OS X any terminal application will let you have the <- key send a ^H (which is something it should do in the first place).

**Closed by vigna** 2020-06-18 12:07 UTC
